In [21]:
from pathlib import Path
import numpy as np
from scipy.io import loadmat
import pandas as pd

In [9]:

raw = loadmat("KPG193_ver1_2/network/mat/KPG193_ver1_2.mat")["mpc"][0, 0]

In [11]:
fx_rate = 1000

In [13]:
raw["genthermal"][:, -6:-3] * fx_rate

array([[10084800., 11093280., 12101760.],
       [10084800., 11093280., 12101760.],
       [ 9202380., 10122618., 11042856.],
       [21544800., 23699280., 25853760.],
       [ 2521200.,  2773320.,  3025440.],
       [15127200., 16639920., 18152640.],
       [12606000., 13866600., 15127200.],
       [43089600., 47398560., 51707520.],
       [43089600., 47398560., 51707520.],
       [ 8824200.,  9706620., 10589040.],
       [ 8824200.,  9706620., 10589040.],
       [29624100., 32586510., 35548920.],
       [29624100., 32586510., 35548920.],
       [23699280., 26069208., 28439136.],
       [53323380., 58655718., 63988056.],
       [13866600., 15253260., 16639920.],
       [12606000., 13866600., 15127200.],
       [12606000., 13866600., 15127200.],
       [12606000., 13866600., 15127200.],
       [11345400., 12479940., 13614480.],
       [47398560., 52138416., 56878272.],
       [29624100., 32586510., 35548920.],
       [29624100., 32586510., 35548920.],
       [45782700., 50360970., 5493

In [42]:
segment = raw["genthermal"][:, -3:-1].astype(np.int64) + 1

In [122]:
segment = np.empty((122, 3), dtype=np.int64)
segment[:, 0] = 1
segment[:, 1:] = raw["genthermal"][:, -3:-1].astype(np.int64) + 1

In [123]:
segment

array([[ 1, 13, 25],
       [ 1, 13, 25],
       [ 1, 13, 25],
       [ 1,  4,  7],
       [ 1, 13, 25],
       [ 1, 13, 25],
       [ 1, 13, 25],
       [ 1,  4,  7],
       [ 1,  4,  7],
       [ 1, 13, 25],
       [ 1, 13, 25],
       [ 1,  4,  7],
       [ 1,  4,  7],
       [ 1,  4,  7],
       [ 1,  4,  7],
       [ 1, 13, 25],
       [ 1, 13, 25],
       [ 1, 13, 25],
       [ 1, 13, 25],
       [ 1, 13, 25],
       [ 1,  4,  7],
       [ 1,  4,  7],
       [ 1,  4,  7],
       [ 1,  4,  7],
       [ 1,  4,  7],
       [ 1,  4,  7],
       [ 1,  4,  7],
       [ 1,  4,  7],
       [ 1,  4,  7],
       [ 1,  4,  7],
       [ 1,  4,  7],
       [ 1,  4,  7],
       [ 1,  4,  7],
       [ 1,  4,  7],
       [ 1,  4,  7],
       [ 1,  4,  7],
       [ 1,  4,  7],
       [ 1, 13, 25],
       [ 1, 13, 25],
       [ 1, 13, 25],
       [ 1, 13, 25],
       [ 1, 13, 25],
       [ 1, 13, 25],
       [ 1, 13, 25],
       [ 1, 13, 25],
       [ 1,  9, 17],
       [ 1,  9, 17],
       [ 1,  

In [114]:
def get_status_2022():
    status_2022 = np.empty((365, 24, 122), dtype=np.uint8)
    path_folder_per_unit_status = Path.cwd().resolve() / "KPG193_ver1_2" / "profile" / "commitment_decision"

    for day in range(365):
        status_2022[day] = (
            pd.read_csv(path_folder_per_unit_status / f"commitment_decision_{day + 1}.csv")
            .sort_values(by=["hour", "generator_id"])
            [["status"]]
            .values
            .reshape((24, 122))
        )

    return status_2022.reshape((8760, 122)).transpose()

status_2022 = get_status_2022()

In [115]:
timestamp_2022 = np.arange(np.datetime64("2022-01-01T00"), np.datetime64("2023-01-01T00"))
idx_time_start = np.where(timestamp_2022 == np.datetime64("2022-07-02T00"))[0][0]

In [ ]:
# xd = np.array([
#     0, 1, 1,    1, 1, 0,    0, 0, 0,    0, 0, 0,
# ])

xd = np.array([    # shutdown       # startup
    0, 1, 1,    1, 1, 0,    0, 0, 0,    1, 1, 1,
])

In [143]:
v = np.array((xd[1:] - xd[:-1]) == 1, dtype=np.int64)
w = np.array((xd[1:] - xd[:-1]) == -1, dtype=np.int64)

array([1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0])

In [ ]:
i = 3
s = 1
for tau in range(segment[i][s], segment[i][s+1]):
    print(f"tau={tau}, u_t-tau={xd[0-tau]}, w_t-tau={w[0-tau]}")
    so delta 0 1 2 = 0 so currently no start up cost
    

tau=4, u_t-tau=0, w_t-tau=0
tau=5, u_t-tau=0, w_t-tau=0
tau=6, u_t-tau=0, w_t-tau=0


In [ ]:

just adding equality constrant that like delta 2 = 1 ? 

SyntaxError: invalid syntax (2639240866.py, line 1)